### ISSUE TITLE
yarn package not available

### ISSUE THREAD

**Issue by michelevettone** [mroads/react-native-user-inactivity#5]
Hi, I'm having problem installing your package throug yarn.
The command used is the same found in documentation `yarn add react-native-user-inactivity-check`.

Output error:
error An unexpected error occurred: "https://registry.yarnpkg.com/react-native-user-inactivity-check: Not found".

**Comment by SrZorro** [comment]
@michelevettone the package Is now published at [npmjs.com/package/react-native-user-inactivity-check](https://www.npmjs.com/package/react-native-user-inactivity-check), could you try again if it works? If so, could you close this issue? Thanks.

**Comment by michelevettone** [comment]
Perfect, it is working now! Thank you @SrZorro!
