### ISSUE TITLE
[META] Give ownship of the NPM package to maintainer

### ISSUE THREAD

**Issue by SrZorro** [mroads/react-native-user-inactivity#8]
As stated in issue #6 I published myself the package to NPM to fix it for future users needing this package.

If @saimanideep-mroads @Vijay-mRoads could share your NPM username I will transfer the ownship for the package at [npmjs.com/package/react-native-user-inactivity-check](https://www.npmjs.com/package/react-native-user-inactivity-check), thanks.

**Comment by Vijay-mRoads** [comment]
Hey @SrZorro,

Thank you for bringing this to our notice. Please transfer the ownership to `vijay-mroads`. We'll make sure that we maintain this package. Please let us know when the ownership is transferred.

Thank you.
Vijay

**Comment by SrZorro** [comment]
@Vijay-mRoads ownership transfered 🚀
